function y = BetaFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 28-Apr-2018 11:46:49

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 15;       % First Stopband Frequency
    % Fpass1 = 16;       % First Passband Frequency
    % Fpass2 = 31;       % Second Passband Frequency
    % Fstop2 = 32;       % Second Stopband Frequency
    % Astop1 = 40;       % First Stopband Attenuation (dB)
    % Apass  = 0.45757;  % Passband Ripple (dB)
    % Astop2 = 40;       % Second Stopband Attenuation (dB)
    % Fs     = 1000;     % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'ellip', ...
    %     'MatchExactly', 'both', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.96043532127314 1 1 -1.96005353905229 ...
        0.997928158919119; 1 -1.99035075457334 1 1 -1.98886072417127 ...
        0.998927829683642; 1 -1.95794081286543 1 1 -1.95362809128595 ...
        0.989894497355504; 1 -1.99092745245736 1 1 -1.98409993529715 ...
        0.994551050996538; 1 -1.94167820261428 1 1 -1.93961767680829 ...
        0.970136619294915; 1 -1.99347998226953 1 1 -1.96878018360696 ...
        0.981003817389428; 1 0 -1 1 -1.94023449433328 0.959401202783802], ...
        'ScaleValues', [0.620792925322811; 0.620792925322811; ...
        0.805909660159505; 0.805909660159505; 0.425455337737512; ...
        0.425455337737512; 0.04620150753999; 1]);
end

s = double(x);
y = step(Hd,s);

