function y = beta_filter(x)
%  Preprocess input x
%    This function expects an input vector x.

% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 28-Apr-2018 12:23:24

y = bandpass(x,[16,31],1000,'Steepness',0.9,'ImpulseResponse','iir','StopbandAttenuation',60);
