function Hd = Theta_filter
%THETA_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 22-Jun-2016 11:12:35

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

Fstop1 = 3;               % First Stopband Frequency
Fpass1 = 4;               % First Passband Frequency
Fpass2 = 8;               % Second Passband Frequency
Fstop2 = 9;               % Second Stopband Frequency
Dstop1 = 0.01;              % First Stopband Attenuation
Dpass  = 0.01;              % Passband Ripple
Dstop2 = 0.01;              % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]