function y = thetaFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 29-Jul-2018 01:35:39

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 3;     % First Stopband Frequency
    % Fpass1 = 4;     % First Passband Frequency
    % Fpass2 = 7;     % Second Passband Frequency
    % Fstop2 = 8;     % Second Stopband Frequency
    % Astop1 = 60;    % First Stopband Attenuation (dB)
    % Apass  = 1;     % Passband Ripple (dB)
    % Astop2 = 80;    % Second Stopband Attenuation (dB)
    % Fs     = 2000;  % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'ellip', ...
    %     'MatchExactly', 'both', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.99937455098152 1 1 -1.99912269396862 ...
        0.999605495227769; 1 -1.99987790752493 1 1 -1.99961609224065 ...
        0.999774213142847; 1 -1.99927889814624 1 1 -1.99828535102407 ...
        0.998729808210905; 1 -1.99989410496692 1 1 -1.99903890007275 ...
        0.999210539776467; 1 -1.99872681659446 1 1 -1.99751680254102 ...
        0.997884815632119; 1 -1.99994003107654 1 1 -1.99820579583586 ...
        0.998412920540676; 1 0 -1 1 -1.99745293339458 0.997728964205115], ...
        'ScaleValues', [0.330836851870849; 0.330836851870849; ...
        0.485641761212099; 0.485641761212099; 0.183628046744079; ...
        0.183628046744079; 0.00470707282111814; 1]);
end

s = double(x);
y = step(Hd,s);

